In [2]:
import numpy as np

In [7]:
my_list = [10,20,30,40]

In [8]:
type(my_list)

list

In [9]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
a = np.array([1,2,3]) ##aray oluşturma

In [4]:
type(a)

numpy.ndarray

In [8]:
a.shape ##boyut

(3,)

In [9]:
a.ndim ##kaç boyutlu

1

In [11]:
a.dtype ##veri tipi

dtype('int64')

In [12]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [14]:
b.shape # 2 satır 3 kolon olduğundan dolayı shape yani boyut 2,3 çıktı

(2, 3)

In [15]:
b.ndim

2

In [17]:
b.dtype

dtype('int64')

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [21]:
a + b # yani vektörel olarak alt alta topluyor.

array([5, 7, 9])

In [23]:
a*b # çarpıp tek boyuta düşürdü

array([ 4, 10, 18])

In [29]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [39]:
f = np.random.rand(3,5)

In [40]:
f

array([[0.24822279, 0.2000166 , 0.28718495, 0.97115738, 0.53976463],
       [0.4186193 , 0.92088267, 0.16993046, 0.6975608 , 0.05390184],
       [0.34892432, 0.92600675, 0.35789962, 0.18065631, 0.83959396]])

In [50]:
f[1:3:2]

array([[0.4186193 , 0.92088267, 0.16993046, 0.6975608 , 0.05390184]])

2x3’lük random bir array oluştur

Tüm elemanları 2 ile çarp

İlk satırı al

In [57]:
t = np.random.rand(2,3)
t*2
t[1]

array([0.53532532, 0.43202579, 0.17609594])

1. sadece 2. sütunu al
2. tüm değerlerin ortalamasını bul
3. 0.5'ten büyük olanları filtrele

In [58]:
t

array([[0.119727  , 0.39979162, 0.96925588],
       [0.53532532, 0.43202579, 0.17609594]])

In [81]:
t[:,1]

array([0.39979162, 0.43202579])

In [83]:
t.mean()

np.float64(0.4387035906672556)

In [86]:
t[t>0.5] = 1

In [87]:
t

array([[0.119727  , 0.39979162, 1.        ],
       [1.        , 0.43202579, 0.17609594]])

In [88]:
x = np.array([2, 30])
w = np.array([0.4, 0.02])
b = -1

In [96]:
score = np.dot(x,w)+b

In [105]:
score = float(score)

In [106]:
score

0.40000000000000013

In [109]:
if score > 0:
    tahmin = 1
else:
    tahmin = 0

print(tahmin)

1


# Array Arithmetic
--Listelerde aritmetik işlem yapmak, string birleşitrmek gibi oluyor.<p>
--Örneğin aşağıda 2 listenin toplanması aslında yanyana yazılması anlamına geliyor. <p>
--Ancak Numpy'da arrayler direkt olarak aritmetik işleme uygun şekilde tasarlanmıştır. Yani index index toplanıyor veya çarpılıyor.

In [110]:
my_list1 = [2,3,4]
my_list2 = [5,6,7]

In [111]:
my_list1 + my_list2

[2, 3, 4, 5, 6, 7]

In [112]:
my_array1 = np.array([2,3,4])
my_array2 = np.array([4,5,6])

In [113]:
my_array1 + my_array2

array([ 6,  8, 10])

In [114]:
my_array1 * my_array2

array([ 8, 15, 24])

### arrange - indexing

In [117]:
list(range(0,10)) # liste için range fonksiyonu

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [118]:
np.arange(0,10) # numpy için arange fonksiyonu, 2 değer arasında bir array oluşturur.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
x_array = np.arange(0,20,2)

In [127]:
x_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [128]:
x_array[2]

np.int64(4)

In [129]:
x_array[-2]

np.int64(16)

In [131]:
x_array[1:4] # birinci indexte başla 4. indexte dur.

array([2, 4, 6])

In [133]:
x_array[::-1]

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [134]:
x_array[2:6:3]

array([ 4, 10])

In [136]:
np.random.randn(4,5)

array([[ 0.94225129,  0.57969602,  1.54076483,  0.14070617,  0.12117892],
       [ 1.05964743,  1.74841253,  0.83247253,  0.52187107, -1.22095019],
       [-0.14184895,  0.47753291, -0.40092098,  0.07383856, -0.01539258],
       [ 1.12227111,  2.46678506,  1.02614741,  1.67858002,  0.7266031 ]])

### matrixler

In [146]:
x_matrix = np.array([[2,3],[5,6],[10,12]]) # 3 satır 2 kolonuk matrix

In [149]:
x_matrix

array([[ 2,  3],
       [ 5,  6],
       [10, 12]])

In [147]:
x_matrix.shape # matrixin satır ve kolon bilgisini almak

(3, 2)

In [145]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [148]:
x_matrix[1][0]

np.int64(5)

In [152]:
X = np.array([
 [1, 2],
 [3, 4]
])

w = np.array([10, 1])

In [153]:
np.dot(X,w)


array([12, 34])

In [154]:
X = np.array([
    [1, 0],
    [2, 3],
    [4, 1]
])

w = np.array([2, 5])

In [155]:
np.dot(X,w)


array([ 2, 19, 13])

In [156]:
# ML Mantığı

Linear Regresiyon temelde şu formülden doğar: y_pred = w * x + b <p>
w --> ağırlık
b --> bias
y --> tahmin

In [158]:
x = np.array([1, 2, 3, 4], dtype=float)
y = np.array([3, 5, 7, 9], dtype=float)

In [159]:
x

array([1., 2., 3., 4.])

In [160]:
y

array([3., 5., 7., 9.])

In [179]:
y_pred = 2*x+0

In [180]:
y_pred

array([2., 4., 6., 8.])

In [181]:
error = y_pred - y

In [182]:
error

array([-1., -1., -1., -1.])

In [183]:
squared_errror = error **2

In [184]:
loss = np.mean(squared_errror)

In [185]:
loss

np.float64(1.0)

In [186]:
y_pred
error
loss

np.float64(1.0)